---
- include: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
- include: mac.yml
  when: ansible_distribution == "MacOSX"

- name: Download vim-plug from github
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim

